Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"
    
    config.ssh.insert_key = true

    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.define "otmanS", primary: true do |server|
        server.vm.hostname = "otmanS"
        server.vm.network "private_network", ip: "192.168.56.110"

        server.vm.provider "virtualbox" do |vb|
            vb.name = "otmanS"
            vb.memory = 2048
            vb.cpus = 2
        end

        server.vm.provider "libvirt" do |libvirt|
            libvirt.memory = 2048
            libvirt.cpus = 2
        end

        server.vm.provision "file", source: "confs", destination: "/tmp/confs"
        server.vm.provision "shell", path: "scripts/argocd.sh"
    end
end
